export const COLLECTIONS_REQUEST =  'COLLECTIONS_REQUEST'
export const COLLECTIONS_SUCCESS =  'COLLECTIONS_SUCCESS'
export const COLLECTIONS_FAIL =  'COLLECTIONS_FAIL'

export const COLLECTION_SAVE_REQUEST =  'COLLECTION_SAVE_REQUEST'
export const COLLECTION_SAVE_SUCCESS =  'COLLECTION_SAVE_SUCCESS'
export const COLLECTION_SAVE_FAIL =  'COLLECTION_SAVE_FAIL'
