export const PERSONAL_INFO_SAVE_REQUEST = 'PERSONAL_INFO_SAVE_REQUEST';
export const PERSONAL_INFO_SAVE_SUCCESS = 'PERSONAL_INFO_SAVE_SUCCESS';
export const PERSONAL_INFO_SAVE_FAIL = 'PERSONAL_INFO_SAVE_FAIL';

export const PERSONAL_INFO_UPDATE_REQUEST = 'PERSONAL_INFO_UPDATE_REQUEST';
export const PERSONAL_INFO_UPDATE_SUCCESS = 'PERSONAL_INFO_UPDATE_SUCCESS';
export const PERSONAL_INFO_UPDATE_FAIL = 'PERSONAL_INFO_UPDATE_FAIL';

export const DATA_SAVE_REQUEST = 'DATA_SAVE_REQUEST';
export const DATA_SAVE_SUCCESS = 'DATA_SAVE_SUCCESS';
export const DATA_SAVE_FAIL = 'DATA_SAVE_FAIL';

export const DATA_SINGLE_REQUEST = 'DATA_SINGLE_REQUEST';
export const DATA_SINGLE_SUCCESS = 'DATA_SINGLE_SUCCESS';
export const DATA_SINGLE_FAIL = 'DATA_SINGLE_FAIL';

export const DATA_UPDATE_REQUEST = 'DATA_UPDATE_REQUEST';
export const DATA_UPDATE_SUCCESS = 'DATA_UPDATE_SUCCESS';
export const DATA_UPDATE_FAIL = 'DATA_UPDATE_FAIL';

export const BENEFICIARY_SAVE_REQUEST = 'BENEFICIARY_SAVE_REQUEST';
export const BENEFICIARY_SAVE_SUCCESS = 'BENEFICIARY_SAVE_SUCCESS';
export const BENEFICIARY_SAVE_FAIL = 'BENEFICIARY_SAVE_FAIL';

export const BENEFICIARY_UPDATE_REQUEST = 'BENEFICIARY_UPDATE_REQUEST';
export const BENEFICIARY_UPDATE_SUCCESS = 'BENEFICIARY_UPDATE_SUCCESS';
export const BENEFICIARY_UPDATE_FAIL = 'BENEFICIARY_UPDATE_FAIL';

export const BENEFICIARY_LIST_REQUEST = 'BENEFICIARY_LIST_REQUEST';
export const BENEFICIARY_LIST_SUCCESS = 'BENEFICIARY_LIST_SUCCESS';
export const BENEFICIARY_LIST_FAIL = 'BENEFICIARY_LIST_FAIL';

export const PLANHOLDERS_REQUEST = 'PLANHOLDERS_REQUEST';
export const PLANHOLDERS_SUCCESS = 'PLANHOLDERS_SUCCESS';
export const PLANHOLDERS_FAIL = 'PLANHOLDERS_FAIL';